# Generated by Django 5.2.7 on 2025-11-26 05:17

import Gestion_Salud.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Salud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Centro')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo de Centro')),
                ('is_public', models.BooleanField(default=True, verbose_name='¿Es Público?')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='area_asignada',
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_ingreso',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='ultima_actualizacion',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='prevision',
        ),
        migrations.AddField(
            model_name='paciente',
            name='birth_date',
            field=models.DateField(default='2000-01-01', verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='first_name',
            field=models.CharField(default='Desconocido', max_length=100, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='institutional_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Institucional'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='last_name_father',
            field=models.CharField(default='Desconocido', max_length=100, verbose_name='Apellido Paterno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='last_name_mother',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(help_text='Ej: 11.222.333-K', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=Gestion_Salud.fields.RutField(max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(verbose_name='Fecha de Ingreso')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Alta')),
                ('discharge_details', models.TextField(blank=True, null=True, verbose_name='Detalles del Alta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('healthcare_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Salud.healthcarecenter', verbose_name='Centro de Salud')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='Gestion_Salud.paciente', verbose_name='Paciente')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
