# Generated by Django 5.2.7 on 2025-12-03 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Salud', '0002_healthcarecenter_remove_paciente_area_asignada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='area',
            field=models.CharField(choices=[('UCI', 'Unidad de Cuidados Intensivos (UCI)'), ('HOSPITALIZACION', 'Hospitalización'), ('URGENCIAS', 'Urgencias'), ('PARTO', 'Sala de Parto'), ('LABORATORIO', 'Laboratorio'), ('BANCO_SANGRE', 'Banco de Sangre'), ('IMAGENOLOGIA', 'Imagenología'), ('SALA_ESPERA', 'Sala de Espera'), ('ODONTOLOGIA', 'Odontología')], default='SALA_ESPERA', max_length=50, verbose_name='Área / Sector'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='status',
            field=models.CharField(choices=[('TRATAMIENTO', 'En Tratamiento'), ('PRE_OPERATORIO', 'Pre Operatorio'), ('POST_OPERATORIO', 'Post Operatorio'), ('ALTA', 'En Alta')], default='TRATAMIENTO', max_length=50, verbose_name='Estado del Paciente'),
        ),
        migrations.CreateModel(
            name='ClinicalObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Observación / Evolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Médico Tratante')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='Gestion_Salud.patientrecord', verbose_name='Ficha Clínica')),
            ],
            options={
                'verbose_name': 'Observación Clínica',
                'verbose_name_plural': 'Observaciones Clínicas',
                'ordering': ['-created_at'],
            },
        ),
    ]
