# Generated by Django 5.2.7 on 2025-12-03 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Salud', '0003_patientrecord_area_patientrecord_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalobservation',
            options={'ordering': ['created_at'], 'verbose_name': 'Observación Clínica', 'verbose_name_plural': 'Observaciones Clínicas'},
        ),
        migrations.RemoveField(
            model_name='clinicalobservation',
            name='text',
        ),
        migrations.AddField(
            model_name='clinicalobservation',
            name='detalle',
            field=models.TextField(default='Sin detalle', verbose_name='Detalle Evolución'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='medico_tratante',
            field=models.ForeignKey(blank=True, limit_choices_to={'position': 'MEDICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Médico Tratante'),
        ),
        migrations.AlterField(
            model_name='clinicalobservation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Médico Responsable'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='area',
            field=models.CharField(choices=[('UCI', 'Unidad de Cuidados Intensivos (UCI)'), ('URGENCIAS', 'Urgencias'), ('HOSPITALIZACION', 'Hospitalización'), ('PARTO', 'Sala de Parto'), ('LABORATORIO', 'Laboratorio'), ('IMAGENOLOGIA', 'Imagenología'), ('PABELLON', 'Pabellón'), ('ESPERA', 'Sala de Espera')], default='ESPERA', max_length=50, verbose_name='Área / Sector'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='status',
            field=models.CharField(choices=[('ESPERA', 'En Espera'), ('TRATAMIENTO', 'En Tratamiento'), ('PRE_OPERATORIO', 'Pre Operatorio'), ('POST_OPERATORIO', 'Post Operatorio'), ('ALTA', 'En Alta')], default='ESPERA', max_length=50, verbose_name='Estado del Paciente'),
        ),
    ]
